### ISSUE TITLE
./gfe_driver -G /root/code/datasets/dota/dota-league.properties -u -l stinger -w -g 1 -d output_results.sqlite3

### ISSUE THREAD

**Issue by Yongze-zzz** [cwida/gfe_driver#3]
dear authors!
Thanks for yours codes,there are some bugs after successfully make.

./gfe_driver -G /root/code/datasets/dota-league.properties -u -l stinger7-ref -w 1 -d results.sqlite3
[driver] Initialising ...
[driver] Save the current configuration properties in results.sqlite3
bug
[get_srcdir_from_makefile] WARNING: Cannot read the result from make: No such file or directory
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    39656 abort      ./gfe_driver -G /root/code/datasets/dota-league.properties -u -l stinger7-ref

**Comment by whatsthecraic** [comment]
Hi @Yongze-zzz,
mmmh this is coming from [here](https://github.com/whatsthecraic/libcommon/blob/43344372d5d4c773af1b9dd24009928c3bb7c18f/src/system_introspection.cpp#L98). It simply executes this command: `make -n -p | awk '/^srcdir\s*:?=/ {print $NF}'`. I don't actually know what's the problem. Could you perhaps try to execute that command, in the terminal, from the same folder you're running the program? Both `make` and `awk` should be present in the system.

In case we can set up a video call to go through & see what's the actual issue.

**Comment by Yongze-zzz** [comment]
> 
Thanks for your reply, I simply set a breakpoint to debug, and then commented params.push_back(P{"git_commit",common::git_last_commit()}) in configuration.cpp. Although I don't know what this function is for, this successfully enabled me to drive sortledton. I'm wondering if I want to manually provide a graphlog of a small graph easy.properties what its properties file should look like.
![1668166611740](https://user-images.githubusercontent.com/70116723/201332588-4a530f99-eacc-42a7-bbcd-730f4f24df36.png)
I have .v file and .e file like dota-league.properties.

**Comment by whatsthecraic** [comment]
You can indeed comment out that line. It only records in the final output (a sqlite3 database) the git commit of the current codebase. 

About small graphs, you can find a few examples in <repo>/tests/graphs/ldbc_graphalytics/example-directed.* and <repo>/tests/graphs/ldbc_graphalytics/example-undirected.* . It's the same format used by LDBC Graphalytics.

meta.vertices and meta.edges are the number of vertices and edges in the files easy.v and easy.e respectively. The others are the arguments for the Graphalytics kernels, e.g. source-vertex is the root vertex in the BFS and SSSP algorithms. These are described in the [Graphalytics docs](https://ldbcouncil.org/ldbc_graphalytics_docs/graphalytics_spec.pdf).

**Comment by Yongze-zzz** [comment]
Appreciate!I wiill try.Sortledton is a very good job, I will continue to follow.Let's keep in touch

**Comment by Yongze-zzz** [comment]
I tried to reproduce your Concurrent Read-Write Workload experiment, using the example dataset of ldbc, using the following command: ./gfe_driver -u -R 1 -d results.sqlite3 -l sortledton.4 -G /gfe_driver_change/tests/graphs/ldbc_graphalytics/e ample-undirected.properties -w 2 -r 1 --blacklist sssp,cdlp,pagerank,wcc,lcc --log /gfe_driver_change/tests/graphs/ldbc_graphalytics/e ample -undirected.graphlog --aging_timeout 2h --mixed_workload true --block_size 512, I didn't locate where the update happened. Did you call the update function of sortledton? Or just use the aging2_worker.execute_update() function to update the graph.Aging experiments are mainly run here.
![image](https://user-images.githubusercontent.com/70116723/201513444-d509c47b-c02a-44e5-9b23-25da91d35fed.png)
