### ISSUE TITLE
Is it possible to have the Makefile.am?

### ISSUE THREAD

**Issue by Jiboxiake** [cwida/gfe_driver#5]
I'm trying to add more graph libraries into GFE driver. I'm wondering if I can have Makefile.am so it will make adding the library easier. Thanks.

**Comment by whatsthecraic** [comment]
The build doesn't use Automake, there is no Makefile.am at all. Rather it uses the autoconf script [configure.ac](https://github.com/cwida/gfe_driver/blob/master/configure.ac) to create the Makefile from [Makefile.in](https://github.com/cwida/gfe_driver/blob/master/Makefile.in).
